const EPS = 0.02;
const A_MAX = 20;
function deltaTop(inp){return inp.yOut-inp.m*inp.xIn}
function deltaBottom(inp){return inp.yIn-inp.m*inp.xOut}
function deltaIn(inp){return inp.yIn-inp.m*inp.xIn}
function safeRatio(inp){const dx=inp.xOut-inp.xIn;return dx===0?Infinity:(inp.yIn-inp.yOut)/dx}
export function liquidToGasRatio(inp){return safeRatio(inp)}
export function liquidFlow(inp){return inp.V*liquidToGasRatio(inp)}
export function absorptionFactor(inp){return liquidToGasRatio(inp)/inp.m}
export function minLiquidToGasRatio(inp){const d=inp.yIn/inp.m-inp.xIn;return d===0?Infinity:(inp.yIn-inp.yOut)/d}
export function feasibility(inp){const top=deltaTop(inp),bottom=deltaBottom(inp);if(!(top>0))return{feasible:false,pinch:'top',reason:'The operating line reaches equilibrium at the top: y_out must exceed m·x_in.'};if(!(bottom>0))return{feasible:false,pinch:'bottom',reason:'The operating line reaches equilibrium at the bottom: x_out must remain below y_in/m.'};const r=liquidToGasRatio(inp);if(!(r>0)||!Number.isFinite(r))return{feasible:false,pinch:'bottom',reason:'The terminal compositions do not define a positive finite liquid-to-gas ratio.'};return{feasible:true,pinch:null,reason:'Operating and equilibrium lines remain separated.'}}
function kremserN(A,R){return Math.abs(A-1)<1e-6?(R-1)+(A-1)*R*(1-R)/2:Math.log1p((A-1)*R)/Math.log(A)-1}
export function theoreticalStages(inp){const A=absorptionFactor(inp),dt=deltaTop(inp),di=deltaIn(inp);if(!(A>0)||!(dt>0)||!(di>0))return NaN;const R=di/dt,arg=1+(A-1)*R;if(!(arg>0))return NaN;return kremserN(A,R)}
export function stepStaircase(inp){const A=absorptionFactor(inp),dt=deltaTop(inp),di=deltaIn(inp),x0=inp.xIn,y0=inp.yOut;if(!(A>0)||!(dt>0)||!(di>0))return{vertices:[{x:x0,y:y0}],fullSteps:0,N:NaN};const vertices=[{x:x0,y:y0}],N=theoreticalStages(inp);if(!Number.isFinite(N))return{vertices,fullSteps:0,N};let y=y0,fullSteps=0,risers=0;while(risers<200){const xEq=y/inp.m,yCandidate=inp.yOut+A*(y-inp.m*inp.xIn),tol=Math.max(1e-14,Math.abs(inp.yIn)*1e-12);vertices.push({x:xEq,y});if(yCandidate<inp.yIn-tol){vertices.push({x:xEq,y:yCandidate});y=yCandidate;fullSteps++;risers++;continue}vertices.push({x:xEq,y:inp.yIn});if(Math.abs(yCandidate-inp.yIn)<=tol)fullSteps++;break}return{vertices,fullSteps,N}}
export function ntuAnalytic(inp){const A=absorptionFactor(inp),dt=deltaTop(inp),di=deltaIn(inp);if(!(A>0)||!(dt>0)||!(di>0))return NaN;const R=di/dt,b=1-1/A,arg=1+b*(R-1);if(!(arg>0))return NaN;return Math.abs(b)<1e-8?(R-1)-b*(R-1)*(R-1)/2:Math.log1p(b*(R-1))/b}
export function ntuNumeric(inp,n=1000){n=Math.max(2,Math.floor(n));if(n%2)n++;const lov=liquidToGasRatio(inp),f=y=>{const x=inp.xIn+(y-inp.yOut)/lov;return 1/(y-inp.m*x)},a=inp.yOut,b=inp.yIn,h=(b-a)/n;let sum=f(a)+f(b);for(let i=1;i<n;i++)sum+=(i%2?4:2)*f(a+i*h);return h*sum/3}
export function ntuLogMean(inp){const top=deltaTop(inp),bottom=deltaBottom(inp);if(!(top>0)||!(bottom>0))return NaN;const dy=inp.yIn-inp.yOut;if(Math.abs(bottom-top)<=Math.max(1e-15,Math.abs(top)*1e-14))return dy/top;return dy/((bottom-top)/Math.log(bottom/top))}
export function hetp(inp){const A=absorptionFactor(inp);if(!(A>0))return NaN;const g=Math.abs(A-1)<1e-5?1+(A-1)/2-(A-1)*(A-1)/6:A*Math.log(A)/(A-1);return inp.HOG*g}
export function packedHeight(inp){return inp.HOG*ntuAnalytic(inp)}
export function actualTrays(inp){const N=theoreticalStages(inp);if(!Number.isFinite(N)||!(inp.Eo>0))return NaN;return Math.ceil(N/inp.Eo)}
export function trayColumnHeight(inp){return actualTrays(inp)*inp.traySpacing+inp.hTop+inp.hBot}
export function gasProfilePacked(inp,zFromTop){const Z=packedHeight(inp),NOG=ntuAnalytic(inp);if(!(Z>=0)||!(NOG>=0))return NaN;const z=Math.min(Math.max(0,zFromTop),Z),A=absorptionFactor(inp),dt=deltaTop(inp),b=1-1/A;if(Math.abs(A-1)<1e-8)return inp.yOut+dt*(z/inp.HOG);return inp.m*inp.xIn+dt*(Math.exp(b*z/inp.HOG)-1/A)/b}
export function gasProfileTray(inp,j){const n=actualTrays(inp),N=theoreticalStages(inp);if(!(n>=1)||!Number.isFinite(N))return NaN;const jj=Math.min(Math.max(1,j),n+1),s=1+(jj-1)*N/n,A=absorptionFactor(inp),dt=deltaTop(inp);if(Math.abs(A-1)<1e-8)return inp.m*inp.xIn+s*dt;return inp.m*inp.xIn+dt*(Math.pow(A,s)-1)/(A-1)}
export function clampYOut(inp,yOutRaw){const di=deltaIn(inp),lower=inp.m*inp.xIn+EPS*di,upper=inp.yIn-EPS*di,value=Math.min(Math.max(yOutRaw,lower),upper),at=yOutRaw<lower?'lower':yOutRaw>upper?'upper':null;return{value,clamped:at!==null,at,pinch:at==='lower'?'top':null}}
export function clampXOut(inp,xOutRaw){const pinch=inp.yIn/inp.m,lower=inp.xIn+(inp.yIn-inp.yOut)/(A_MAX*inp.m),upper=inp.xIn+(1-EPS)*(pinch-inp.xIn),value=Math.min(Math.max(xOutRaw,lower),upper),at=xOutRaw<lower?'lower':xOutRaw>upper?'upper':null;return{value,clamped:at!==null,at,pinch:at==='upper'?'bottom':null}}
function axes(inp){return{xMax:1.15*(inp.yIn/inp.m),yMax:1.15*inp.yIn}}
export function solve(inp){const f=feasibility(inp),LoV=liquidToGasRatio(inp),L=liquidFlow(inp),A=absorptionFactor(inp),N=theoreticalStages(inp),staircase=stepStaircase(inp),NOG=ntuAnalytic(inp),HETP=hetp(inp),Z=packedHeight(inp),nActual=actualTrays(inp),ZTray=trayColumnHeight(inp),LoVmin=minLiquidToGasRatio(inp),Amin=LoVmin/inp.m,xOutPinch=inp.yIn/inp.m,top=deltaTop(inp),bottom=deltaBottom(inp),logMean=top>0&&bottom>0?(Math.abs(bottom-top)<=Math.max(1e-15,Math.abs(top)*1e-14)?top:(bottom-top)/Math.log(bottom/top)):NaN;return{feasible:f.feasible,pinch:f.pinch,reason:f.reason,LoV,L,A,N,staircase,NOG,HETP,Z,HOG:inp.HOG,nActual,ZTray,LoVmin,Amin,xOutPinch,driving:{top,bottom,logMean},terminals:{xIn:inp.xIn,yOut:inp.yOut,xOut:inp.xOut,yIn:inp.yIn,m:inp.m},inputs:{V:inp.V,Eo:inp.Eo,traySpacing:inp.traySpacing,hTop:inp.hTop,hBot:inp.hBot},profiles:{packed:Array.from({length:101},(_,i)=>{const z=Z*i/100;return{z,y:gasProfilePacked(inp,z)}}),tray:Array.from({length:Math.max(1,Number.isFinite(nActual)?nActual+1:1)},(_,i)=>{const j=i+1;return{z:nActual>0?(j-1)*ZTray/nActual:0,y:gasProfileTray(inp,j)}})},axes:axes(inp)}}
